### ISSUE TITLE
I'm keep getting "DNS name doesn't exist"

### ISSUE THREAD

**Issue by abdazahran** [Arno0x/DNSExfiltrator#6]
Hello,
First of all, many thanks for your efforts and help.

I'm keeping getting this message "DNS name doesn't exist" however my DNS and Google DNS can resolve mydomain.com with no issues and NS record is pointing to my kali machine.
Is there anything missing, please? by the way I'm using win10 as the source and the kali with python 2.7 as a target.

**Comment by Arno0x** [comment]
Duplicate with issue #5.
